# Generated by Django 4.1.7 on 2023-04-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Booking_date', models.DateField()),
                ('Booked_on', models.DateField(auto_now_add=True)),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.doctors')),
            ],
        ),
    ]
